#!/bin/bash

systemctl daemon-reload

systemctl enable ros.service
systemctl start ros.service

systemctl enable ros-watchdog.service
systemctl start ros-watchdog.service --no-block

systemctl enable roscore.service
systemctl start roscore.service --no-block

systemctl enable ros-project.service
systemctl start ros-project.service

systemctl enable ros-robot.service
systemctl start ros-robot.service

systemctl enable ros-sensors.service
systemctl start ros-sensors.service