#!/usr/bin/env python3

import subprocess
import time
import sys
import signal
import threading

import systemd.daemon

running = True

def _handler(*args):
    global running
    running = False

signal.signal(signal.SIGINT, _handler)
signal.signal(signal.SIGTERM, _handler)

code = 1
while running and code != 0:
    code, output = subprocess.getstatusoutput('bash -c "source /opt/ros/noetic/setup.bash && rostopic list"')
    
    if code == 0:
        break

    time.sleep(2)

print('ROS Core Detected')
systemd.daemon.notify('READY=1')

while running:
    code, _ = subprocess.getstatusoutput('bash -c "source /opt/ros/noetic/setup.bash && rostopic list"')

    if code != 0:
        print('ROS Core lost... Shutting down...')
        sys.exit(1)

    time.sleep(2)
